title: Bokun Zheng
email: your.email@example.com
description: >-
  Personal website of Bokun Zheng, including education, research, projects, and blog posts.
baseurl: ""
url: "https://zzzzzbk.github.io"
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - education.md
  - research.md
  - projects.md
  - blog.md
