title: Bokun Zheng
email: zhengbk@hotmail.com
description: >-
  Personal website of Bokun Zheng
baseurl: ""
url: "https://zzzzzbk.github.io"
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - research.md
  - projects.md
  - blog.md
